
import numpy as np
import scipy.linalg as la
from linear_solver import assemble_swe_matrices

class LandauCalculator:
    def __init__(self, params, N, L_domain=None):
        """
        Initialize Calculator with physical parameters and resolution.
        
        Args:
            params: Dictionary of physical parameters (Fr, Cf, beta, etc.)
            N: Chebyshev resolution (number of nodes - 1)
            L_domain: Physical length scale (if needed for normalization)
        """
        self.params = params
        self.N = N
        # Standard Chebyshev Grid
        self.y_cheb = np.cos(np.pi * np.arange(N + 1) / N)
        self.D_cheb = self.cheb_diff_matrix(N)
        
        # Solution Storage
        self.eigenvalue_linear = None
        self.vector_linear = None      # Psi_11
        self.vector_adjoint = None     # Psi_dag
        
    def cheb_diff_matrix(self, N):
        """Standard Chebyshev differentiation matrix."""
        # TODO: Refactor to import from common utility if available
        # Simple implementation for self-containment
        x = np.cos(np.pi * np.arange(N + 1) / N)
        c = np.hstack(([2], np.ones(N - 1), [2])) * (-1)**np.arange(N + 1)
        X = np.tile(x, (N + 1, 1))
        dX = X - X.T
        D = (c[:, np.newaxis] / c[np.newaxis, :]) / (dX + np.eye(N + 1))
        D = D - np.diag(np.sum(D, axis=1))
        return D

    def solve_linear_adjoint(self, sigma_width, k_wavenumber):
        """
        Solve both the Direct A and Adjoint A^H Eigenproblems.
        Finds the critical mode and its corresponding adjoint.
        """
        # 1. Assemble Matrices
        # Note: assemble_swe_matrices returns A, B where A is LHS, B is RHS mass matrix
        # A X = omega B X
        A, B = assemble_swe_matrices(
            self.D_cheb, self.y_cheb, 
            alpha=k_wavenumber,
            beta=self.params.get('beta', 10.0),
            Cf=self.params.get('Cf', 0.01),
            Fr=self.params.get('Fr', 0.5),
            N_curv=0.0, # Assuming straight channel base for simplified nonlinear expansion first
            sigma_width=sigma_width,
            params=self.params
        )
        
        # 2. Direct Solve
        vals, vecs = la.eig(A, B)
        
        # Filter for the physical bar mode (finite eigenvalues)
        # Remove Infs generated by algebraic BCs in B matrix
        finite_mask = np.isfinite(vals)
        vals_finite = vals[finite_mask]
        vecs_finite = vecs[:, finite_mask]
        
        if len(vals_finite) == 0:
            raise ValueError("No finite eigenvalues found.")
            
        # Select most unstable mode
        idx = np.argmax(np.real(vals_finite))
        self.eigenvalue_linear = vals_finite[idx]
        self.vector_linear = vecs_finite[:, idx]
        
        # 3. Adjoint Solve
        # Adjoint problem: A^H Y = conj(omega) B^H Y
        # We solve eig(A.conj().T, B.conj().T)
        vals_adj, vecs_adj = la.eig(A.conj().T, B.conj().T)
        
        # Find the mode corresponding to the same eigenvalue
        # Expected: lambda_adj = conj(lambda_direct)
        target = np.conj(self.eigenvalue_linear)
        dist = np.abs(vals_adj - target)
        idx_adj = np.argmin(dist)
        
        self.vector_adjoint = vecs_adj[:, idx_adj]
        
        # Normalize Orthogonality: <Psi_adj, B Psi_direct> = 1
        # Inner product definition: integral over domain.
        # Approximation: Clenshaw-Curtis weights or simple trapz/dot
        # Here we use simple dot product for discrete vectors if weights matrix W included in definition?
        # Standard vector dot: y^H * B * x
        
        # Metric weight integration?
        # For now, standard Hermitian inner product
        norm_factor = np.vdot(self.vector_adjoint, B @ self.vector_linear)
        self.vector_adjoint = self.vector_adjoint / np.conj(norm_factor)
        
        return self.eigenvalue_linear

    def extract_components(self, vector):
        """Unpack state vector into u, v, eta, zb."""
        M = self.N + 1
        u = vector[0:M]
        v = vector[M:2*M]
        eta = vector[2*M:3*M]
        zb = vector[3*M:4*M]
        return u, v, eta, zb

    def compute_nonlinear_forcing(self, k_wavenumber):
        """
        Construct Forcing Vectors for Order epsilon^2.
        Returns:
            forcing_20: Vector (size 4M) for Mean Flow Distortion (k=0)
            forcing_22: Vector (size 4M) for Second Harmonic (k=2*alpha)
        """
        if self.vector_linear is None:
            raise ValueError("Linear mode not solved yet.")
            
        u1, v1, eta1, zb1 = self.extract_components(self.vector_linear)
        u1_conj = np.conj(u1)
        v1_conj = np.conj(v1)
        # ... others if needed
        
        # Grid Operators
        D = self.D_cheb
        ik = 1j * k_wavenumber
        
        # --- 1. Second Harmonic Forcing (Psi_22) ---
        # Driving terms approx: - (u1 * du1/dx + ...)
        # N_22 ~ - ( u1 * ik * u1 + v1 * D * u1 )
        
        # Derivatives of Mode 1
        u1_x = ik * u1
        u1_y = D @ u1
        v1_x = ik * v1
        v1_y = D @ v1
        
        # u-Momentum Forcing (Equation 1)
        # N_u_22 = - (u1 u1_x + v1 u1_y) - friction...
        # Note: Symbolic verified structure: u*ux + v*uy
        # We need the negative because L(X2) = - N(X1, X1) usually
        N_u_22 = - (u1 * u1_x + v1 * u1_y)
        
        # v-Momentum Forcing (Equation 2)
        # N_v_22 = - (u1 v1_x + v1 v1_y + C * u1^2)
        C_val = 0.0 # self.params.get('N_curv', 0) # Curvature
        N_v_22 = - (u1 * v1_x + v1 * v1_y + C_val * u1**2)
        
        # Mass Forcing (Equation 3)
        # div( (eta-zb)*u )
        # = d((eta1-zb1)*u1)/dx + ...
        h1 = eta1 - zb1
        flux_u = h1 * u1
        flux_v = h1 * v1
        N_eta_22 = - (ik * flux_u + D @ flux_v)
        
        # Exner Forcing (Equation 4)
        # div(Qs) -> d( qs )/dx
        # qs ~ beta * u0^(beta-1) * u ...
        # Quadratic part derived: beta(beta-1) * u1 * u1_x
        # Scaled by base flow U0? assuming normalized.
        beta = self.params.get('beta', 3.0)
        # From symbolic: U0**(b-2) ...
        # Simplified: beta * (beta-1) * u1 * u1_x
        N_zb_22 = - (beta * (beta - 1) * u1 * u1_x)
        
        # Pack Vector 22
        vals_22 = [N_u_22, N_v_22, N_eta_22, N_zb_22]
        forcing_22 = np.concatenate(vals_22)
        
        # --- 2. Mean Flow Distortion (Psi_20) ---
        # Driven by Reynolds Stresses from interaction of Mode 1 and Conjugate
        # Terms: u1 v1_conj + u1_conj v1, etc.
        # Mean of (A u1 e + cc)(B v1 e + cc) = A B* u1 v1* + A* B u1* v1
        # = |A|^2 (u1 v1* + u1* v1) = |A|^2 * 2 * Real(u1 v1*)
        
        # Reynolds Stresses
        uu_mean = 2 * np.real(u1 * u1_conj)
        vv_mean = 2 * np.real(v1 * v1_conj)
        uv_mean = 2 * np.real(u1 * v1_conj)
        
        # Derivatives of Mean Stresses
        # For k=0, d/dx = 0. Only d/dy (cross-stream) matters.
        # u-Mom: - v * du/dy - u * dv/dy ... = - d(uv)/dy + u dv/dy - v du/dy?
        # Conservative form: - div(uu, uv) -> - d(uv)/dy for x-mom
        N_u_20 = - (D @ uv_mean)
        
        # v-Mom: - div(vu, vv) -> - d(vv)/dy
        # Plus Centrifugal: C * u^2_mean
        N_v_20 = - (D @ vv_mean) - (C_val * uu_mean)
        
        # Mass: - div( h u ) -> - d( (eta-zb) v )/dy
        # flux_v_mean = 2 * Re( (eta1-zb1) * v1* )
        h1 = eta1 - zb1
        hv_mean = 2 * np.real(h1 * v1_conj)
        N_eta_20 = - (D @ hv_mean)
        
        # Exner: - d(Qs)/dx = 0 for k=0 ?
        # If axis-symmetric, d/ds=0. So no mean bed evolution from linear flux div.
        # But secondary currents might drive slope effects.
        # For now, Exner forcing ~ 0.
        N_zb_20 = np.zeros_like(u1)
        
        vals_20 = [N_u_20, N_v_20, N_eta_20, N_zb_20]
        forcing_20 = np.concatenate(vals_20)
        
        return forcing_20, forcing_22

    def compute_nonlinear_forcing_mean_isolated(self, vec_a, vec_b, k):
        """
        Computes Mean Flow forcing term driven by interaction of vec_a and vec_b_conj.
        """
        u_a, v_a, eta_a, zb_a = self.extract_components(vec_a)
        u_b, v_b, eta_b, zb_b = self.extract_components(vec_b)
        u_b = u_b.conj(); v_b = v_b.conj(); eta_b = eta_b.conj()
        
        adv_u_1 = u_a * (-1j * k * u_b) + v_a * (self.D_cheb @ u_b)
        adv_u_2 = u_b * (1j * k * u_a) + v_b * (self.D_cheb @ u_a)
        forcing_u = -(adv_u_1 + adv_u_2)
        
        adv_v_1 = u_a * (-1j * k * v_b) + v_a * (self.D_cheb @ v_b)
        adv_v_2 = u_b * (1j * k * v_a) + v_b * (self.D_cheb @ v_a)
        forcing_v = -(adv_v_1 + adv_v_2)
        
        flux_x = u_a * eta_b + u_b * eta_a
        flux_y = v_a * eta_b + v_b * eta_a
        forcing_h = -(0 + self.D_cheb @ flux_y)
        
        forcing_zb = np.zeros_like(forcing_u)
        
        M = self.N + 1
        F = np.zeros(4 * M, dtype=complex)
        F[0:M] = forcing_u; F[M:2*M] = forcing_v; F[2*M:3*M] = forcing_h; F[3*M:] = forcing_zb
        return F

    def compute_nonlinear_forcing_harmonic_mixed(self, vec_a, vec_b, k):
        """
        Computes forcing for Sum Mode (A + B) at 2k.
        """
        u_a, v_a, eta_a, _ = self.extract_components(vec_a)
        u_b, v_b, eta_b, _ = self.extract_components(vec_b)
        
        term1 = u_a * (1j*k*u_b) + v_a * (self.D_cheb @ u_b)
        term2 = u_b * (1j*k*u_a) + v_b * (self.D_cheb @ u_a)
        forcing_u = -(term1 + term2)
        
        term1_v = u_a * (1j*k*v_b) + v_a * (self.D_cheb @ v_b)
        term2_v = u_b * (1j*k*v_a) + v_b * (self.D_cheb @ v_a)
        forcing_v = -(term1_v + term2_v)
        
        flux_x = u_a * eta_b + u_b * eta_a
        flux_y = v_a * eta_b + v_b * eta_a
        div = 1j*(2*k)*flux_x + self.D_cheb @ flux_y
        forcing_h = -div
        
        M = self.N + 1
        F = np.zeros(4 * M, dtype=complex)
        F[0:M] = forcing_u; F[M:2*M] = forcing_v; F[2*M:3*M] = forcing_h
        return F

    def compute_cubic_interaction_mixed(self, vec_lin, vec_sec, k_lin, k_sec):
        """
        Interaction between a Linear Mode and a Second Order Mode.
        """
        u1, v1, eta1, _ = self.extract_components(vec_lin)
        u2, v2, eta2, _ = self.extract_components(vec_sec)
        
        adv_u_12 = u1 * (1j*k_sec*u2) + v1 * (self.D_cheb @ u2)
        adv_u_21 = u2 * (1j*k_lin*u1) + v2 * (self.D_cheb @ u1)
        f_u = -(adv_u_12 + adv_u_21)
        
        adv_v_12 = u1 * (1j*k_sec*v2) + v1 * (self.D_cheb @ v2)
        adv_v_21 = u2 * (1j*k_lin*v1) + v2 * (self.D_cheb @ v1)
        f_v = -(adv_v_12 + adv_v_21)
        
        flux_x = u1 * eta2 + u2 * eta1
        flux_y = v1 * eta2 + v2 * eta1
        k_out = k_lin + k_sec
        f_h = -(1j*k_out*flux_x + self.D_cheb @ flux_y)
        
        M = self.N + 1
        F = np.zeros(4 * M, dtype=complex)
        F[0:M] = f_u; F[M:2*M] = f_v; F[2*M:3*M] = f_h
        return F

    def compute_cubic_interaction(self, u1, v1, eta1, zb1, X20, X22, k_c):
        """
        Compute Cubic Forcing terms N3 proportional to e^{ikx}.
        Interactions: (Mode 1 * Mode 20) + (Mode 1_conj * Mode 22)
        """
        # Unpack X20, X22
        u20, v20, eta20, zb20 = self.extract_components(X20)
        u22, v22, eta22, zb22 = self.extract_components(X22)
        
        D = self.D_cheb
        ik = 1j * k_c
        
        # Terms: u * du/dx ...
        # 1. Interaction (1, 20): A * |A|^2
        # u_term_1 = u1 * du20/dx (0) + v1 * du20/dy + u20 * du1/dx + v20 * du1/dy
        u_term_1 = (v1 * (D @ u20)) + (u20 * (ik * u1)) + (v20 * (D @ u1))
        
        # 2. Interaction (1*, 22): A* * A^2 = |A|^2 A
        # u_term_2 = u1* * du22/dx + v1* * du22/dy + u22 * du1*/dx + v22 * du1*/dy
        # du22/dx = 2ik * u22
        # du1*/dx = -ik * u1*
        u1_c = np.conj(u1)
        v1_c = np.conj(v1)
        u_term_2 = (u1_c * (2*ik * u22)) + (v1_c * (D @ u22)) + \
                   (u22 * (-ik * u1_c)) + (v22 * (D @ u1_c))
                   
        N_u_3 = - (u_term_1 + u_term_2)
        
        # v-Mom, Mass, Exner similar ...
        # Simplified placeholder: just return u-mom contribution for dominant physics check
        zeros = np.zeros_like(u1)
        N_3 = np.concatenate([N_u_3, zeros, zeros, zeros])
        
        return N_3

    def solve_second_order(self, forcing, k_out, omega_shift):
        """
        Solve linear system for 2nd order modes.
        (A(k_out) - omega_shift * B(k_out)) X = Forcing
        """
        # Assemble matrices for the output wavenumber
        A, B = assemble_swe_matrices(
            self.D_cheb, self.y_cheb,
            alpha=k_out,
            beta=self.params.get('beta', 10.0),
            Cf=self.params.get('Cf', 0.01),
            Fr=self.params.get('Fr', 0.5),
            N_curv=0.0,
            sigma_width=0.0, # Base state assumption
            params=self.params
        )
        
        # Operator
        L = A - omega_shift * B
        
        # Boundary Conditions for 2nd order?
        # Regular BCs usually apply (v=0 at walls).
        # assemble_swe_matrices handles BCs in A.
        # But we need to be careful forcing respects BC rows (usually 0).
        # We manually zero out forcing at boundaries just in case.
        # Rows 1 (v) and M+1 (v)? No, row index logic.
        M = self.N + 1
        for r_idx in [0, M-1]:
             glob_r = 1 * M + r_idx # v-momentum
             forcing[glob_r] = 0.0
        
        # Solve
        try:
            X = la.solve(L, forcing)
        except la.LinAlgError:
            # Fallback for singular matrix (e.g. k=0 resonance)
            # Add small regularization or fix pressure
            pin = 1e-6
            X = la.solve(L + pin*np.eye(L.shape[0]), forcing)
            
        return X

    def compute_landau_coefficients(self, sigma_width, k_c):
        """
        Main driver to compute gamma.
        1. Solve Adjoint
        2. Compute Forcing N2
        3. Solve X22, X20
        4. Compute Cubic Projection
        """
        # 1. Solve Linear & Adjoint
        omega = self.solve_linear_adjoint(sigma_width, k_c)
        print(f"Critical Omega: {omega:.4f}")
        
        # 2. Forcing
        N20, N22 = self.compute_nonlinear_forcing(k_c)
        
        # 3. Solve 2nd Order
        # Psi_22: driven by A^2. Time dep e^{2 i omega t} -> shift = 2*omega
        X22 = self.solve_second_order(N22, 2*k_c, 2*omega)
        
        # Psi_20: driven by |A|^2. Time dep e^{2 sigma t}.
        # At critical threshold, sigma~0 -> shift = 0 (or 2*real(omega))
        X20 = self.solve_second_order(N20, 0.0, 2*np.real(omega))
        
        # 4. Cubic Interaction
        # Extract components again for clarity
        u1, v1, eta1, zb1 = self.extract_components(self.vector_linear)
        
        N3 = self.compute_cubic_interaction(u1, v1, eta1, zb1, X20, X22, k_c)
        
        # Gamma = < Psi_adj, N3 > / < Psi_adj, B Psi_1 >
        # We already normalized Psi_adj s.t. denominator is 1 (if B Psi_1 used in norm)
        # Check normalization in solve_linear_adjoint:
        # norm_factor = dot(adj, B @ vec) -> adj = adj / conj(norm)
        # Denom becomes 1.
        
        gamma = np.vdot(self.vector_adjoint, N3)
        
        print(f"Computed Gamma: {gamma}")
        return gamma
